%YAML:1.0
cameras:
     - {T_SC:
        [ 0.0148655429818, -0.999880929698, 0.00414029679422, -0.0216401454975,
          0.999557249008, 0.0149672133247, 0.025715529948, -0.064676986768,
          -0.0257744366974, 0.00375618835797, 0.999660727178, 0.00981073058949,
           0.0, 0.0, 0.0, 1.0],
        image_dimension: [752, 480],
        distortion_coefficients: [-0.28340811217, 0.0739590738929, 0.000193595028569, 1.76187114545e-05],
        distortion_type: radialtangential,
        focal_length: [458.654880721, 457.296696463],
        principal_point: [367.215803962, 248.37534061]}

     - {T_SC:
        [ 0.0125552670891, -0.999755099723, 0.0182237714554, -0.0198435579556,
          0.999598781151, 0.0130119051815, 0.0251588363115, 0.0453689425024,
          -0.0253898008918, 0.0179005838253, 0.999517347078, 0.00786212447038,
           0.0, 0.0, 0.0, 1.0],
        image_dimension: [752, 480],
        distortion_coefficients: [-0.283683654496, 0.0745128430929, -0.000104738949098, -3.55590700274e-05],
        distortion_type: radialtangential,
        focal_length: [457.587426604, 456.13442556],
        principal_point: [379.99944652, 255.238185386]}


# additional camera parameters
camera_parameters:
    timestamp_tolerance: 0.005 # [s] stereo frame out-of-sync tolerance
    image_delay: 0.00 # [s] timestamp_camera_correct = timestamp_camera - image_delay
    online_calibration: # some parameters to set the online 
        do_extrinsics: false # Do we online-calibrate extrinsics?
        sigma_r: 0.01 # T_SCi position prior stdev [m]
        sigma_alpha: 0.05 # T_SCi orientation prior stdev [rad]

imu_parameters:
    #IMU.NoiseGyro: 1.7e-04 # 1.6968e-04
    #IMU.NoiseAcc: 2.0e-03 # 2.0000e-3
    #IMU.GyroWalk: 1.9393e-05
    #IMU.AccWalk: 3.e-03 # 3.0000e-3
    use: true
    a_max: 176.0 # acceleration saturation [m/s^2]
    g_max: 7.8 # gyro saturation [rad/s]
    sigma_g_c: 20.0e-4 # gyro noise density [rad/s/sqrt(Hz)]
    sigma_a_c: 20.0e-3 # accelerometer noise density [m/s^2/sqrt(Hz)]
    sigma_bg: 0.01 # gyro bias prior [rad/s]
    sigma_ba: 0.1 # accelerometer bias prior [m/s^2]
    sigma_gw_c: 20.0e-5 # 4.0e-6 # gyro drift noise density [rad/s^s/sqrt(Hz)]
    sigma_aw_c: 20.0e-3 # 4.0e-5 # accelerometer drift noise density [m/s^2/sqrt(Hz)]
    g: 9.81007 # Earth's acceleration due to gravity [m/s^2]
    g0: [ 0.0, 0.0, 0.0 ] # initial gyro bias [rad/s]
    a0: [ -0.02, 0.12, 0.06 ] #[ -0.05, 0.09, 0.01 ] # initial accelerometer bias [m/s^2]
    #g0: [ -0.00183371, 0.0257634, 0.0787383] # initial gyro bias [rad/s]
    #a0: [ 0.00437839, 0.13191, 0.101086] # initial accelerometer bias [m/s^2]
    # tranform Body-Sensor (IMU)
    T_BS:
        [1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 1.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 1.0000]

# frontend: detection etc. 
frontend_parameters:
    detection_threshold: 36.0 #42.0 # detection threshold. By default the uniformity radius in pixels
    absolute_threshold: 150.0 # absolute Harris corner threshold (noise floor)
    matching_threshold: 60.0 # BRISK descriptor matching threshold
    octaves: 0 # number of octaves for detection. 0 means single-scale at highest resolution
    max_num_keypoints: 700 # restrict to a maximum of this many keypoints per image (strongest ones)
    keyframe_overlap: 0.59 # minimum field-of-view overlap
    use_cnn: false # use the CNN (if available) to filter out dynamic content / sky
    parallelise_detection: false # Run parallel detect & describe.

# estimator parameters
estimator_parameters:
    num_keyframes: 5 # number of keyframes in optimisation window
    num_loop_closure_frames: 5 # number of loop closure frames in optimisation window
    num_imu_frames: 3 # number of frames linked by most recent nonlinear IMU error terms
    do_loop_closures: true # whether to do VI-SLAM or VIO
    do_final_ba: false # Whether to run a full final BA
    enforce_realtime: false # whether to limit the time budget for optimisation 
    realtime_min_iterations: 3 # minimum number of iterations always performed
    realtime_max_iterations: 10 # never do more than these, even if not converged
    realtime_time_limit: 0.035 # time budget for realtime optimisation [s]
    realtime_num_threads: 4 # number of threads for the realtime optimisation
    full_graph_iterations: 15 # don't do more than these for the full (background) optimisation
    full_graph_num_threads: 2 # number of threads for the full (background) optimisation

# some options for how and what to output
output_parameters:
    display_matches: false  # displays debug video and matches. May be slow.
    display_overhead: false # debug overhead image. Is slow.
    publish_imu_propagated_state: false # Should the state that is propagated with IMU messages be published or just the optimised ones?

